<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration
{
    public function up():void
    {
        Schema::create('facturas_orden',function(Blueprint$table){$table->uuid('id')->primary();$table->string('numero',30)->unique();$table->foreignUuid('orden_id')->constrained('ordenes_trabajo')->restrictOnDelete();$table->string('cliente_tipo_documento',30);$table->string('cliente_documento',50);$table->string('cliente_nombre',180);$table->string('cliente_direccion');$table->string('cliente_email');$table->string('vehiculo_placa',20);$table->decimal('subtotal',14,2);$table->decimal('descuento',14,2)->default(0);$table->decimal('base_impuesto',14,2);$table->decimal('tasa_impuesto',5,2)->default(0);$table->decimal('impuesto',14,2)->default(0);$table->decimal('total',14,2);$table->char('moneda',3)->default('USD');$table->string('estado',20)->default('emitida');$table->timestampTz('emitida_en');$table->date('vence_en')->nullable();$table->text('observaciones')->nullable();$table->foreignUuid('emitida_por')->constrained('users')->restrictOnDelete();$table->timestampTz('anulada_en')->nullable();$table->foreignUuid('anulada_por')->nullable()->constrained('users')->nullOnDelete();$table->text('motivo_anulacion')->nullable();$table->timestamps();$table->index(['orden_id','estado']);$table->index('emitida_en');});
        Schema::create('factura_orden_lineas',function(Blueprint$table){$table->uuid('id')->primary();$table->foreignUuid('factura_id')->constrained('facturas_orden')->restrictOnDelete();$table->string('tipo',20);$table->uuid('referencia_id')->nullable();$table->string('codigo',60)->nullable();$table->string('descripcion',200);$table->decimal('cantidad',14,3);$table->decimal('precio_unitario',14,2);$table->decimal('subtotal',14,2);$table->timestampTz('created_at')->useCurrent();$table->index(['factura_id','tipo']);});
        Schema::create('factura_orden_historial',function(Blueprint$table){$table->uuid('id')->primary();$table->foreignUuid('factura_id')->constrained('facturas_orden')->restrictOnDelete();$table->string('evento',30);$table->jsonb('datos')->nullable();$table->foreignUuid('usuario_id')->constrained('users')->restrictOnDelete();$table->timestampTz('created_at')->useCurrent();$table->index(['factura_id','created_at']);});
        DB::statement("CREATE UNIQUE INDEX facturas_orden_activa_unique ON facturas_orden (orden_id) WHERE estado = 'emitida'");DB::statement("ALTER TABLE facturas_orden ADD CONSTRAINT facturas_orden_estado_check CHECK (estado IN ('emitida','anulada'))");DB::statement("ALTER TABLE facturas_orden ADD CONSTRAINT facturas_orden_moneda_check CHECK (moneda = 'USD')");DB::statement('ALTER TABLE facturas_orden ADD CONSTRAINT facturas_orden_valores_check CHECK (subtotal >= 0 AND descuento >= 0 AND descuento <= subtotal AND base_impuesto = subtotal - descuento AND tasa_impuesto >= 0 AND tasa_impuesto <= 100 AND impuesto >= 0 AND total = base_impuesto + impuesto)');DB::statement("ALTER TABLE facturas_orden ADD CONSTRAINT facturas_orden_anulacion_check CHECK ((estado = 'emitida' AND anulada_en IS NULL AND anulada_por IS NULL AND motivo_anulacion IS NULL) OR (estado = 'anulada' AND anulada_en IS NOT NULL AND anulada_por IS NOT NULL AND motivo_anulacion IS NOT NULL))");DB::statement("ALTER TABLE factura_orden_lineas ADD CONSTRAINT factura_lineas_tipo_check CHECK (tipo IN ('servicio','repuesto'))");DB::statement('ALTER TABLE factura_orden_lineas ADD CONSTRAINT factura_lineas_valores_check CHECK (cantidad > 0 AND precio_unitario >= 0 AND subtotal >= 0)');DB::statement("ALTER TABLE factura_orden_historial ADD CONSTRAINT factura_historial_evento_check CHECK (evento IN ('emitida','anulada'))");
    }
    public function down():void{Schema::dropIfExists('factura_orden_historial');Schema::dropIfExists('factura_orden_lineas');Schema::dropIfExists('facturas_orden');}
};
