<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration
{
    public function up():void
    {
        Schema::create('pagos',function(Blueprint$table){$table->uuid('id')->primary();$table->string('numero',30)->unique();$table->foreignUuid('orden_id')->constrained('ordenes_trabajo')->restrictOnDelete();$table->decimal('monto',14,2);$table->char('moneda',3)->default('USD');$table->string('metodo',30);$table->string('referencia',120)->nullable();$table->string('comprobante_numero',40)->unique();$table->text('observaciones')->nullable();$table->string('estado',20)->default('registrado');$table->timestampTz('pagado_en');$table->foreignUuid('registrado_por')->constrained('users')->restrictOnDelete();$table->timestampTz('anulado_en')->nullable();$table->foreignUuid('anulado_por')->nullable()->constrained('users')->nullOnDelete();$table->text('motivo_anulacion')->nullable();$table->timestamps();$table->index(['orden_id','estado']);$table->index('pagado_en');});
        Schema::create('pago_historial',function(Blueprint$table){$table->uuid('id')->primary();$table->foreignUuid('pago_id')->constrained('pagos')->restrictOnDelete();$table->string('evento',30);$table->decimal('monto',14,2);$table->jsonb('datos')->nullable();$table->foreignUuid('usuario_id')->constrained('users')->restrictOnDelete();$table->timestampTz('created_at')->useCurrent();$table->index(['pago_id','created_at']);});
        DB::statement("ALTER TABLE pagos ADD CONSTRAINT pagos_monto_check CHECK (monto > 0)");DB::statement("ALTER TABLE pagos ADD CONSTRAINT pagos_moneda_check CHECK (moneda = 'USD')");DB::statement("ALTER TABLE pagos ADD CONSTRAINT pagos_metodo_check CHECK (metodo IN ('efectivo','tarjeta','transferencia','otro'))");DB::statement("ALTER TABLE pagos ADD CONSTRAINT pagos_estado_check CHECK (estado IN ('registrado','anulado'))");DB::statement("ALTER TABLE pagos ADD CONSTRAINT pagos_anulacion_check CHECK ((estado = 'registrado' AND anulado_en IS NULL AND anulado_por IS NULL AND motivo_anulacion IS NULL) OR (estado = 'anulado' AND anulado_en IS NOT NULL AND anulado_por IS NOT NULL AND motivo_anulacion IS NOT NULL))");DB::statement("ALTER TABLE pago_historial ADD CONSTRAINT pago_historial_evento_check CHECK (evento IN ('registrado','anulado'))");DB::statement('ALTER TABLE pago_historial ADD CONSTRAINT pago_historial_monto_check CHECK (monto > 0)');
    }
    public function down():void{Schema::dropIfExists('pago_historial');Schema::dropIfExists('pagos');}
};
