<?php
namespace Src\Facturacion\Application\Controllers;
use App\Http\Controllers\Controller;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Inertia\Inertia;use Inertia\Response;use Src\Auditoria\Application\Services\RegistrarAuditoria;use Src\Facturacion\Application\Services\GestionarFacturaOrden;use Src\Facturacion\Infrastructure\Models\FacturaOrdenEloquentModel;use Src\Facturacion\Infrastructure\Requests\AnularFacturaOrdenRequest;use Src\Facturacion\Infrastructure\Requests\EmitirFacturaOrdenRequest;use Src\OrdenTrabajo\Infrastructure\Models\OrdenTrabajoEloquentModel;
class FacturacionWebController extends Controller
{
    public function index(Request$r):Response{$buscar=trim((string)$r->input('buscar'));$facturas=FacturaOrdenEloquentModel::with('orden:id,numero')->whereHas('orden',fn($q)=>$q->visiblePara($r->user()))->when($buscar,fn($q)=>$q->where(fn($s)=>$s->where('numero','ilike',"%{$buscar}%")->orWhere('cliente_nombre','ilike',"%{$buscar}%")->orWhere('cliente_documento','ilike',"%{$buscar}%")->orWhereHas('orden',fn($o)=>$o->where('numero','ilike',"%{$buscar}%"))))->latest('emitida_en')->paginate(20)->withQueryString();return Inertia::render('Facturacion/index',['facturas'=>$facturas,'buscar'=>$buscar]);}
    public function show(Request$r,FacturaOrdenEloquentModel$factura):Response{$this->autorizar($r,$factura->orden_id);$factura->load(['orden:id,numero','lineas','historial'=>fn($q)=>$q->latest('created_at')]);return Inertia::render('Facturacion/show',['factura'=>$factura]);}
    public function store(EmitirFacturaOrdenRequest$r,OrdenTrabajoEloquentModel$orden,GestionarFacturaOrden$s,RegistrarAuditoria$a):RedirectResponse{$this->autorizar($r,$orden->id);$factura=$s->emitir($orden,$r->validated(),$r->user()->id);$a->registrar('factura_orden.emitida','factura_orden',$factura->id,['orden_id'=>$orden->id,'total'=>$factura->total],$r);$destino=$r->user()->can('facturas.ver')?route('facturacion.show',$factura):route('ordenes.show',$orden);return redirect($destino)->with('success',"Factura {$factura->numero} emitida.");}
    public function anular(AnularFacturaOrdenRequest$r,FacturaOrdenEloquentModel$factura,GestionarFacturaOrden$s,RegistrarAuditoria$a):RedirectResponse{$this->autorizar($r,$factura->orden_id);$s->anular($factura,$r->validated('motivo'),$r->user()->id);$a->registrar('factura_orden.anulada','factura_orden',$factura->id,['motivo'=>$r->validated('motivo')],$r);return back()->with('success','Factura anulada sin eliminar su historial.');}
    private function autorizar(Request$r,string$ordenId):void{abort_unless(OrdenTrabajoEloquentModel::whereKey($ordenId)->visiblePara($r->user())->exists(),403);}
}
