<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { Head, router, usePage } from '@inertiajs/vue3'
import { route } from 'ziggy-js'
import { usePermissions } from '../../composables/usePermissions'

interface Especialidad { id: string; codigo: string; nombre: string; descripcion?: string; estado: string; mecanicos_count: number; servicios_count: number }
interface Servicio { id: string; codigo: string; nombre: string; descripcion?: string; especialidad?: string; especialidadId?: string; duracionMinutos: number; precioBase: string; estado: string }
const props = defineProps<{ especialidades: Especialidad[]; servicios: Servicio[] }>()
const { can } = usePermissions(); const page = usePage(); const errors = computed<Record<string, string>>(() => page.props.errors as Record<string, string>); const procesando = ref(false)
const especialidad = reactive({ codigo: '', nombre: '', descripcion: '' }); const servicio = reactive({ codigo: '', nombre: '', descripcion: '', especialidadId: '', duracionMinutos: 60, precioBase: '0.00' })
const opciones = computed(() => props.especialidades.filter(e => e.estado === 'activo').map(e => ({ label: e.nombre, value: e.id })))
function guardarEspecialidad() { procesando.value = true; router.post(route('especialidades.store'), especialidad, { preserveScroll: true, onSuccess: () => Object.assign(especialidad, { codigo: '', nombre: '', descripcion: '' }), onFinish: () => { procesando.value = false } }) }
function guardarServicio() { procesando.value = true; router.post(route('servicios.store'), servicio, { preserveScroll: true, onSuccess: () => Object.assign(servicio, { codigo: '', nombre: '', descripcion: '', especialidadId: '', duracionMinutos: 60, precioBase: '0.00' }), onFinish: () => { procesando.value = false } }) }
function toggle(tipo: 'especialidad'|'servicio', item: Especialidad|Servicio) { const estado = item.estado === 'activo' ? 'inactivo' : 'activo'; router.patch(route(`${tipo === 'especialidad' ? 'especialidades' : 'servicios'}.estado`, item.id), { estado }, { preserveScroll: true }) }
</script>
<template>
  <Head title="Servicios del taller" />
  <UDashboardPanel><template #header><UDashboardNavbar title="Servicios del taller"><template #leading><UDashboardSidebarCollapse /></template></UDashboardNavbar></template><template #body>
    <div class="grid gap-6 xl:grid-cols-2"><section class="space-y-4"><UCard v-if="can('especialidades.gestionar')"><template #header><h2 class="font-semibold">Nueva especialidad</h2></template><form class="grid gap-4 sm:grid-cols-2" @submit.prevent="guardarEspecialidad"><UFormField label="Código" required :error="errors.codigo"><UInput v-model="especialidad.codigo" class="w-full" /></UFormField><UFormField label="Nombre" required :error="errors.nombre"><UInput v-model="especialidad.nombre" class="w-full" /></UFormField><UFormField class="sm:col-span-2" label="Descripción"><UTextarea v-model="especialidad.descripcion" class="w-full" /></UFormField><div class="sm:col-span-2 text-right"><UButton type="submit" label="Crear especialidad" :loading="procesando" /></div></form></UCard><h2 class="text-lg font-semibold">Especialidades</h2><UCard v-for="e in especialidades" :key="e.id"><div class="flex justify-between"><div><p class="font-semibold">{{ e.codigo }} · {{ e.nombre }}</p><p class="text-sm text-muted">{{ e.mecanicos_count }} mecánicos · {{ e.servicios_count }} servicios</p></div><UBadge :color="e.estado === 'activo' ? 'success' : 'neutral'">{{ e.estado }}</UBadge></div><template #footer><div class="text-right"><UButton v-if="can('especialidades.gestionar')" label="Cambiar estado" size="sm" color="neutral" variant="ghost" @click="toggle('especialidad', e)" /></div></template></UCard></section>
    <section class="space-y-4"><UCard v-if="can('servicios.gestionar')"><template #header><h2 class="font-semibold">Nuevo servicio</h2></template><form class="grid gap-4 sm:grid-cols-2" @submit.prevent="guardarServicio"><UFormField label="Código" required><UInput v-model="servicio.codigo" class="w-full" /></UFormField><UFormField label="Nombre" required><UInput v-model="servicio.nombre" class="w-full" /></UFormField><UFormField label="Especialidad"><USelect v-model="servicio.especialidadId" class="w-full" :items="opciones" /></UFormField><UFormField label="Duración (min)" required><UInput v-model.number="servicio.duracionMinutos" type="number" min="15" class="w-full" /></UFormField><UFormField label="Precio base" required><UInput v-model="servicio.precioBase" type="number" min="0" step="0.01" class="w-full" /></UFormField><UFormField class="sm:col-span-2" label="Descripción"><UTextarea v-model="servicio.descripcion" class="w-full" /></UFormField><div class="sm:col-span-2 text-right"><UButton type="submit" label="Crear servicio" :loading="procesando" /></div></form></UCard><h2 class="text-lg font-semibold">Catálogo de servicios</h2><UCard v-for="s in servicios" :key="s.id"><div class="flex justify-between gap-3"><div><p class="font-semibold">{{ s.codigo }} · {{ s.nombre }}</p><p class="text-sm text-muted">{{ s.especialidad || 'General' }} · {{ s.duracionMinutos }} min · $ {{ s.precioBase }}</p></div><UBadge :color="s.estado === 'activo' ? 'success' : 'neutral'">{{ s.estado }}</UBadge></div><template #footer><div class="text-right"><UButton v-if="can('servicios.gestionar')" label="Cambiar estado" size="sm" color="neutral" variant="ghost" @click="toggle('servicio', s)" /></div></template></UCard></section></div>
  </template></UDashboardPanel>
</template>
