<script setup lang="ts">
import { reactive } from 'vue'
import { Head, Link, router } from '@inertiajs/vue3'
import { route } from 'ziggy-js'

interface Servicio { nombre:string; precio:string; estado:string; observaciones?:string }
interface Orden { id:string;numero:string;estado:string;fallaReportada:string;kilometraje?:number;recibidaEn:string;finalizadaEn?:string;entregadaEn?:string;motivoCancelacion?:string;mecanicos:{nombre:string;activo:boolean}[];diagnosticos:{version:number;diagnostico:string;pruebas?:string;recomendaciones?:string;vigente:boolean;registradoEn:string}[];servicios:Servicio[];repuestos:{codigo:string;nombre:string;cantidad:string;precio:string;revertido:boolean}[];finanzas?:{servicios:string;repuestos:string;total:string;pagado:string;saldo:string;estado:string;pagos:{numero:string;comprobante:string;monto:string;estado:string;pagadoEn:string}[]}}
interface Pagina<T>{data:T[];current_page:number;last_page:number;total:number;prev_page_url:string|null;next_page_url:string|null}
const props=defineProps<{vehiculo:{id:string;placa:string;marca:string;modelo:string;anio:number;color?:string;kilometraje:number;combustible:string;estado:string;observaciones?:string;propietario?:string};ordenes:Pagina<Orden>;filtros:{desde?:string;hasta?:string;estado?:string;servicio?:string};servicios:{id:string;nombre:string}[];puedeVerFinanzas:boolean}>()
const filtros=reactive({desde:props.filtros.desde||'',hasta:props.filtros.hasta||'',estado:props.filtros.estado||'todos',servicio:props.filtros.servicio||'todos'})
const estados=[{label:'Todos los estados',value:'todos'},{label:'Pendiente',value:'pendiente'},{label:'En diagnóstico',value:'en_diagnostico'},{label:'En reparación',value:'en_reparacion'},{label:'Finalizada',value:'finalizada'},{label:'Entregada',value:'entregada'},{label:'Cancelada',value:'cancelada'}]
function filtrar(){router.get(route('historial-vehicular.show',props.vehiculo.id),{desde:filtros.desde||undefined,hasta:filtros.hasta||undefined,estado:filtros.estado==='todos'?undefined:filtros.estado,servicio:filtros.servicio==='todos'?undefined:filtros.servicio},{preserveState:true,replace:true})}
function dinero(v:string){return Number(v).toLocaleString('es-CO',{minimumFractionDigits:2,maximumFractionDigits:2})}
</script>

<template>
  <Head :title="`Historial ${vehiculo.placa}`" />
  <UDashboardPanel>
    <template #header><UDashboardNavbar :title="`Historial · ${vehiculo.placa}`"><template #leading><UDashboardSidebarCollapse /></template><template #right><Link :href="route('historial-vehicular.index')"><UButton label="Volver" icon="i-lucide-arrow-left" color="neutral" variant="outline"/></Link></template></UDashboardNavbar></template>
    <template #body><div class="space-y-6">
      <UCard><div class="grid gap-4 md:grid-cols-[1fr_auto]"><div><div class="flex flex-wrap items-center gap-2"><h1 class="text-2xl font-bold">{{vehiculo.placa}}</h1><UBadge :color="vehiculo.estado==='activo'?'success':'neutral'">{{vehiculo.estado}}</UBadge></div><p class="mt-1 text-lg">{{vehiculo.marca}} {{vehiculo.modelo}} · {{vehiculo.anio}} · {{vehiculo.color||'Sin color'}}</p><p class="mt-2 text-sm text-muted">Propietario actual: {{vehiculo.propietario||'Sin propietario'}} · {{Number(vehiculo.kilometraje).toLocaleString('es-CO')}} km · {{vehiculo.combustible}}</p><p v-if="vehiculo.observaciones" class="mt-3 text-sm">{{vehiculo.observaciones}}</p></div><div class="text-left md:text-right"><p class="text-sm text-muted">Visitas encontradas</p><p class="text-3xl font-semibold">{{ordenes.total}}</p></div></div></UCard>
      <form class="grid gap-3 rounded-lg border border-default p-4 sm:grid-cols-2 xl:grid-cols-5" @submit.prevent="filtrar"><UInput v-model="filtros.desde" type="date"/><UInput v-model="filtros.hasta" type="date"/><USelect v-model="filtros.estado" :items="estados"/><USelect v-model="filtros.servicio" :items="[{label:'Todos los servicios',value:'todos'},...servicios.map(s=>({label:s.nombre,value:s.id}))]"/><UButton type="submit" label="Aplicar filtros" icon="i-lucide-list-filter"/></form>
      <div class="divide-y divide-default overflow-hidden rounded-lg border border-default">
        <article v-for="orden in ordenes.data" :key="orden.id" class="p-4 sm:p-6">
          <header class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><Link :href="route('ordenes.show',orden.id)" class="font-semibold text-primary hover:underline">{{orden.numero}}</Link><UBadge>{{orden.estado}}</UBadge></div><p class="mt-1 text-sm text-muted">Ingreso {{new Date(orden.recibidaEn).toLocaleString('es-CO')}} · {{orden.kilometraje?Number(orden.kilometraje).toLocaleString('es-CO')+' km':'Sin kilometraje'}}</p></div><div class="text-sm sm:text-right"><p v-if="orden.finalizadaEn">Finalizada {{new Date(orden.finalizadaEn).toLocaleDateString('es-CO')}}</p><p v-if="orden.entregadaEn">Entregada {{new Date(orden.entregadaEn).toLocaleDateString('es-CO')}}</p></div></header>
          <div class="mt-5 space-y-5"><section><p class="text-xs font-medium uppercase tracking-wide text-muted">Falla reportada</p><p class="mt-1">{{orden.fallaReportada}}</p><p v-if="orden.motivoCancelacion" class="mt-2 text-sm text-error">Cancelación: {{orden.motivoCancelacion}}</p></section>
            <div class="grid gap-5 lg:grid-cols-2"><section><h3 class="font-semibold">Diagnóstico y recomendaciones</h3><div v-if="orden.diagnosticos.length" class="mt-2 space-y-3"><div v-for="d in orden.diagnosticos" :key="d.version" class="rounded-lg bg-elevated p-3"><div class="flex justify-between"><span class="text-xs text-muted">Versión {{d.version}}</span><UBadge v-if="d.vigente" color="success" size="xs">Vigente</UBadge></div><p class="mt-1">{{d.diagnostico}}</p><p v-if="d.pruebas" class="mt-2 text-sm"><span class="text-muted">Pruebas:</span> {{d.pruebas}}</p><p v-if="d.recomendaciones" class="mt-2 text-sm"><span class="text-muted">Recomendaciones:</span> {{d.recomendaciones}}</p></div></div><p v-else class="mt-2 text-sm text-muted">Sin diagnóstico registrado.</p></section>
              <section><h3 class="font-semibold">Mecánicos responsables</h3><div class="mt-2 flex flex-wrap gap-2"><UBadge v-for="m in orden.mecanicos" :key="m.nombre" :color="m.activo?'primary':'neutral'">{{m.nombre||'Sin nombre'}}{{m.activo?' · actual':' · histórico'}}</UBadge><span v-if="!orden.mecanicos.length" class="text-sm text-muted">Sin asignaciones.</span></div></section></div>
            <div class="grid gap-5 lg:grid-cols-2"><section><h3 class="font-semibold">Servicios realizados</h3><div class="mt-2 divide-y divide-default"><div v-for="s in orden.servicios" :key="s.nombre" class="flex justify-between gap-3 py-2"><div><p>{{s.nombre}}</p><p v-if="s.observaciones" class="text-xs text-muted">{{s.observaciones}}</p></div><div class="text-right"><UBadge size="xs">{{s.estado}}</UBadge><p v-if="puedeVerFinanzas" class="text-sm">$ {{dinero(s.precio)}}</p></div></div><p v-if="!orden.servicios.length" class="py-2 text-sm text-muted">Sin servicios.</p></div></section>
              <section><h3 class="font-semibold">Repuestos utilizados</h3><div class="mt-2 divide-y divide-default"><div v-for="r in orden.repuestos" :key="`${r.codigo}-${r.nombre}`" class="flex justify-between gap-3 py-2" :class="r.revertido?'line-through text-muted':''"><p>{{r.codigo}} · {{r.nombre}}</p><p>{{r.cantidad}}<span v-if="puedeVerFinanzas"> · $ {{dinero(r.precio)}}</span></p></div><p v-if="!orden.repuestos.length" class="py-2 text-sm text-muted">Sin repuestos.</p></div></section></div>
            <section v-if="puedeVerFinanzas&&orden.finanzas" class="rounded-lg border border-default p-4"><div class="flex flex-wrap items-center justify-between gap-3"><div><h3 class="font-semibold">Resumen financiero</h3><p class="text-sm text-muted">Servicios $ {{dinero(orden.finanzas.servicios)}} · Repuestos $ {{dinero(orden.finanzas.repuestos)}}</p></div><UBadge :color="orden.finanzas.estado==='pagado'?'success':orden.finanzas.estado==='vencido'?'error':'warning'">{{orden.finanzas.estado}}</UBadge></div><div class="mt-3 grid grid-cols-3 gap-3 text-sm"><div><p class="text-muted">Total</p><p class="font-semibold">$ {{dinero(orden.finanzas.total)}}</p></div><div><p class="text-muted">Pagado</p><p class="font-semibold">$ {{dinero(orden.finanzas.pagado)}}</p></div><div><p class="text-muted">Saldo</p><p class="font-semibold">$ {{dinero(orden.finanzas.saldo)}}</p></div></div></section>
          </div>
        </article><UCard v-if="!ordenes.data.length"><p class="py-8 text-center text-muted">No hay visitas para los filtros seleccionados.</p></UCard>
      </div>
      <div class="flex items-center justify-between"><p class="text-sm text-muted">Página {{ordenes.current_page}} de {{ordenes.last_page}}</p><div class="flex gap-2"><UButton label="Anterior" color="neutral" variant="outline" :disabled="!ordenes.prev_page_url" @click="ordenes.prev_page_url&&router.visit(ordenes.prev_page_url)"/><UButton label="Siguiente" color="neutral" variant="outline" :disabled="!ordenes.next_page_url" @click="ordenes.next_page_url&&router.visit(ordenes.next_page_url)"/></div></div>
    </div></template>
  </UDashboardPanel>
</template>
