<script setup lang="ts">
import { reactive, ref, watch } from 'vue'
import { Head, Link, router } from '@inertiajs/vue3'
import { route } from 'ziggy-js'

interface Servicio { nombre:string; precio:string; estado:string; observaciones?:string }
interface Orden { id:string;numero:string;estado:string;fallaReportada:string;kilometraje?:number;recibidaEn:string;finalizadaEn?:string;entregadaEn?:string;motivoCancelacion?:string;mecanicos:{nombre:string;activo:boolean}[];diagnosticos:{version:number;estado:string;diagnostico:string;pruebas?:string;recomendaciones?:string;vigente:boolean;registradoEn:string}[];servicios:Servicio[];repuestos:{codigo:string;nombre:string;cantidad:string;precio:string;revertido:boolean}[];finanzas?:{servicios:string;repuestos:string;total:string;pagado:string;saldo:string;estado:string;factura?:{id:string;numero:string;estado:string};pagos:{numero:string;comprobante:string;monto:string;estado:string;pagadoEn:string}[]}}
interface Pagina<T>{data:T[];current_page:number;last_page:number;total:number;prev_page_url:string|null;next_page_url:string|null}
const props=defineProps<{vehiculo:{id:string;placa:string;marca:string;modelo:string;anio:number;color?:string;kilometraje:number;combustible:string;estado:string;observaciones?:string;propietario?:string};ordenes:Pagina<Orden>;filtros:{desde?:string;hasta?:string;estado?:string;servicio?:string;buscar?:string;orden?:string};servicios:{id:string;nombre:string}[];puedeVerFinanzas:boolean;modoCliente:boolean}>()
const filtros=reactive({buscar:props.filtros.buscar||'',desde:props.filtros.desde||'',hasta:props.filtros.hasta||'',estado:props.filtros.estado||'todos',servicio:props.filtros.servicio||'todos',orden:props.filtros.orden||'reciente'})
const detalleAbierto=ref<string|null>(null)
const rutaDetalle=props.modoCliente?'mi-historial.show':'historial-vehicular.show'
const estados=[{label:'Todos los estados',value:'todos'},...['pendiente','asignada','en_diagnostico','esperando_aprobacion','esperando_repuestos','en_reparacion','pausada','en_prueba','finalizada','lista_entrega','entregada','cancelada'].map(value=>({label:value.replaceAll('_',' '),value}))]
function filtrar(){router.get(route(rutaDetalle,props.vehiculo.id),{buscar:filtros.buscar||undefined,desde:filtros.desde||undefined,hasta:filtros.hasta||undefined,estado:filtros.estado==='todos'?undefined:filtros.estado,servicio:filtros.servicio==='todos'?undefined:filtros.servicio,orden:filtros.orden},{preserveState:true,replace:true})}
let temporizador:ReturnType<typeof setTimeout>
watch(()=>filtros.buscar,()=>{clearTimeout(temporizador);temporizador=setTimeout(filtrar,350)})
function dinero(v:string){return Number(v).toLocaleString('es-EC',{minimumFractionDigits:2,maximumFractionDigits:2})}
</script>

<template>
  <Head :title="`Historial ${vehiculo.placa}`" />
  <UDashboardPanel>
    <template #header><UDashboardNavbar :title="`${modoCliente?'Mi historial':'Historial'} · ${vehiculo.placa}`"><template #leading><UDashboardSidebarCollapse /></template><template #right><Link :href="route(modoCliente?'mi-historial.index':'historial-vehicular.index')"><UButton label="Volver" icon="i-lucide-arrow-left" color="neutral" variant="outline"/></Link></template></UDashboardNavbar></template>
    <template #body><div class="space-y-6">
      <UCard><div class="grid gap-4 md:grid-cols-[1fr_auto]"><div><div class="flex flex-wrap items-center gap-2"><h1 class="text-2xl font-bold">{{vehiculo.placa}}</h1><UBadge :color="vehiculo.estado==='activo'?'success':'neutral'">{{vehiculo.estado}}</UBadge></div><p class="mt-1 text-lg">{{vehiculo.marca}} {{vehiculo.modelo}} · {{vehiculo.anio}} · {{vehiculo.color||'Sin color'}}</p><p class="mt-2 text-sm text-muted">Propietario actual: {{vehiculo.propietario||'Sin propietario'}} · {{Number(vehiculo.kilometraje).toLocaleString('es-EC')}} km · {{vehiculo.combustible}}</p><p v-if="vehiculo.observaciones" class="mt-3 text-sm">{{vehiculo.observaciones}}</p></div><div class="text-left md:text-right"><p class="text-sm text-muted">Visitas encontradas</p><p class="text-3xl font-semibold">{{ordenes.total}}</p></div></div></UCard>
      <form class="grid gap-3 rounded-lg border border-default bg-default/80 p-4 sm:grid-cols-2 xl:grid-cols-4" @submit.prevent="filtrar"><UInput v-model="filtros.buscar" icon="i-lucide-search" placeholder="Orden, servicio o diagnóstico"/><UInput v-model="filtros.desde" type="date"/><UInput v-model="filtros.hasta" type="date"/><USelect v-model="filtros.estado" :items="estados"/><USelect v-model="filtros.servicio" :items="[{label:'Todos los servicios',value:'todos'},...servicios.map(s=>({label:s.nombre,value:s.id}))]"/><USelect v-model="filtros.orden" :items="[{label:'Más recientes primero',value:'reciente'},{label:'Más antiguos primero',value:'antiguo'}]"/><UButton type="submit" label="Aplicar filtros" icon="i-lucide-list-filter"/></form>
      <div class="divide-y divide-default overflow-hidden rounded-lg border border-default">
        <article v-for="orden in ordenes.data" :key="orden.id" class="p-4 sm:p-6">
          <header class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><span class="font-semibold text-primary">{{orden.numero}}</span><UBadge>{{orden.estado}}</UBadge></div><p class="mt-1 text-sm text-muted">Ingreso {{new Date(orden.recibidaEn).toLocaleString('es-EC')}} · {{orden.kilometraje?Number(orden.kilometraje).toLocaleString('es-EC')+' km':'Sin kilometraje'}}</p></div><div class="flex flex-col items-start gap-2 text-sm sm:items-end"><p v-if="orden.finalizadaEn">Finalizada {{new Date(orden.finalizadaEn).toLocaleDateString('es-EC')}}</p><p v-if="orden.entregadaEn">Entregada {{new Date(orden.entregadaEn).toLocaleDateString('es-EC')}}</p><UButton :label="detalleAbierto===orden.id?'Ocultar detalles':'Ver detalles'" size="sm" color="neutral" variant="outline" :icon="detalleAbierto===orden.id?'i-lucide-chevron-up':'i-lucide-eye'" @click="detalleAbierto=detalleAbierto===orden.id?null:orden.id"/></div></header>
          <div v-if="detalleAbierto===orden.id" class="mt-5 space-y-5"><section><p class="text-xs font-medium uppercase tracking-wide text-muted">Falla reportada</p><p class="mt-1">{{orden.fallaReportada}}</p><p v-if="orden.motivoCancelacion" class="mt-2 text-sm text-error">Cancelación: {{orden.motivoCancelacion}}</p></section>
            <div class="grid gap-5 lg:grid-cols-2"><section><h3 class="font-semibold">Diagnóstico y recomendaciones</h3><div v-if="orden.diagnosticos.length" class="mt-2 space-y-3"><div v-for="d in orden.diagnosticos" :key="d.version" class="rounded-lg bg-elevated p-3"><div class="flex justify-between"><span class="text-xs text-muted">Versión {{d.version}}</span><UBadge v-if="d.vigente" color="success" size="xs">{{ d.estado === 'borrador' ? 'Borrador actual' : 'Publicado actual' }}</UBadge></div><p class="mt-1">{{d.diagnostico}}</p><p v-if="d.pruebas" class="mt-2 text-sm"><span class="text-muted">Pruebas:</span> {{d.pruebas}}</p><p v-if="d.recomendaciones" class="mt-2 text-sm"><span class="text-muted">Recomendaciones:</span> {{d.recomendaciones}}</p></div></div><p v-else class="mt-2 text-sm text-muted">Sin diagnóstico registrado.</p></section>
              <section><h3 class="font-semibold">Mecánicos responsables</h3><div class="mt-2 flex flex-wrap gap-2"><UBadge v-for="m in orden.mecanicos" :key="m.nombre" :color="m.activo?'primary':'neutral'">{{m.nombre||'Sin nombre'}}{{m.activo?' · actual':' · histórico'}}</UBadge><span v-if="!orden.mecanicos.length" class="text-sm text-muted">Sin asignaciones.</span></div></section></div>
            <div class="grid gap-5 lg:grid-cols-2"><section><h3 class="font-semibold">Trabajos y servicios realizados</h3><div class="mt-2 divide-y divide-default"><div v-for="s in orden.servicios" :key="s.nombre" class="flex justify-between gap-3 py-2"><div><p>{{s.nombre}}</p><p v-if="s.observaciones" class="text-xs text-muted">{{s.observaciones}}</p></div><div class="text-right"><UBadge size="xs">{{s.estado}}</UBadge><p v-if="puedeVerFinanzas" class="text-sm">$ {{dinero(s.precio)}}</p></div></div><p v-if="!orden.servicios.length" class="py-2 text-sm text-muted">Sin servicios.</p></div></section>
              <section><h3 class="font-semibold">Repuestos utilizados</h3><div class="mt-2 divide-y divide-default"><div v-for="r in orden.repuestos" :key="`${r.codigo}-${r.nombre}`" class="flex justify-between gap-3 py-2" :class="r.revertido?'line-through text-muted':''"><p>{{r.codigo}} · {{r.nombre}}</p><p>{{r.cantidad}}<span v-if="puedeVerFinanzas"> · $ {{dinero(r.precio)}}</span></p></div><p v-if="!orden.repuestos.length" class="py-2 text-sm text-muted">Sin repuestos.</p></div></section></div>
             <section v-if="puedeVerFinanzas&&orden.finanzas" class="rounded-lg border border-default p-4"><div class="flex flex-wrap items-center justify-between gap-3"><div><h3 class="font-semibold">Resumen financiero</h3><p class="text-sm text-muted">Mano de obra $ {{dinero(orden.finanzas.servicios)}} · Repuestos $ {{dinero(orden.finanzas.repuestos)}}</p><p class="mt-1 text-sm"><span class="text-muted">Factura:</span> {{orden.finanzas.factura?.numero||'No emitida'}}</p></div><UBadge :color="orden.finanzas.estado==='pagado'?'success':orden.finanzas.estado==='vencido'?'error':'warning'">{{orden.finanzas.estado}}</UBadge></div><div class="mt-3 grid grid-cols-3 gap-3 text-sm"><div><p class="text-muted">Valor total</p><p class="font-semibold">$ {{dinero(orden.finanzas.total)}}</p></div><div><p class="text-muted">Total pagado</p><p class="font-semibold">$ {{dinero(orden.finanzas.pagado)}}</p></div><div><p class="text-muted">Saldo</p><p class="font-semibold">$ {{dinero(orden.finanzas.saldo)}}</p></div></div></section>
          </div>
        </article><UCard v-if="!ordenes.data.length"><p class="py-8 text-center text-muted">No hay visitas para los filtros seleccionados.</p></UCard>
      </div>
      <div class="flex items-center justify-between"><p class="text-sm text-muted">Página {{ordenes.current_page}} de {{ordenes.last_page}}</p><div class="flex gap-2"><UButton label="Anterior" color="neutral" variant="outline" :disabled="!ordenes.prev_page_url" @click="ordenes.prev_page_url&&router.visit(ordenes.prev_page_url)"/><UButton label="Siguiente" color="neutral" variant="outline" :disabled="!ordenes.next_page_url" @click="ordenes.next_page_url&&router.visit(ordenes.next_page_url)"/></div></div>
    </div></template>
  </UDashboardPanel>
</template>
