<?php
namespace Src\Auth\Application\Controllers;
use App\Http\Controllers\Controller;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;use Inertia\Inertia;use Inertia\Response;use Src\Auditoria\Application\Services\RegistrarAuditoria;use Src\Auth\Infrastructure\Models\RoleEloquentModel;use Src\Auth\Infrastructure\Models\UserEloquentModel;use Src\Auth\Infrastructure\Requests\ActualizarRolesUsuarioRequest;use Src\Auth\Infrastructure\Requests\ActualizarUsuarioRequest;use Src\Auth\Infrastructure\Requests\CambiarEstadoUsuarioRequest;use Src\Auth\Infrastructure\Requests\CrearUsuarioRequest;
class UserWebController extends Controller
{
    public function index(Request$r):Response{$buscar=trim((string)$r->input('buscar'));$estado=$r->input('estado');$rol=$r->input('rol');$usuarios=UserEloquentModel::with('roles:id,name')->when($buscar,fn($q)=>$q->where(fn($s)=>$s->where('name','ilike',"%{$buscar}%")->orWhere('email','ilike',"%{$buscar}%")))->when($estado!==null&&$estado!=='',fn($q)=>$q->where('activo',$estado==='activo'))->when($rol,fn($q)=>$q->role($rol))->orderBy('name')->paginate(15)->withQueryString();return Inertia::render('Auth/Users/index',['usuarios'=>$usuarios,'roles'=>$this->catalogoRoles(),'filtros'=>['buscar'=>$buscar,'estado'=>$estado,'rol'=>$rol],'usuarioActualId'=>$r->user()->id]);}
    public function create():Response{return Inertia::render('Auth/Users/form',['usuario'=>null,'roles'=>$this->catalogoRoles(false),'esCliente'=>false]);}
    public function store(CrearUsuarioRequest$r,RegistrarAuditoria$a):RedirectResponse{abort_unless($r->user()->can('roles.administrar'),403);$usuario=DB::transaction(function()use($r,$a){$d=$r->safe()->except('role_ids');$usuario=UserEloquentModel::create([...$d,'activo'=>true]);$roles=RoleEloquentModel::whereIn('id',$r->validated('role_ids'))->get();$usuario->syncRoles($roles);$a->registrar('usuario.creado','usuario',$usuario->id,['email'=>$usuario->email,'roles'=>$roles->pluck('name')->all()],$r);return$usuario;});return redirect()->route('usuarios.index')->with('success','Usuario creado.');}
    public function edit(UserEloquentModel$usuario):Response{$usuario->load('roles:id,name');$esCliente=$usuario->hasRole('Cliente');return Inertia::render('Auth/Users/form',['usuario'=>['id'=>$usuario->id,'name'=>$usuario->name,'email'=>$usuario->email,'activo'=>$usuario->activo,'roleIds'=>$usuario->roles->pluck('id')],'roles'=>$this->catalogoRoles(false),'esCliente'=>$esCliente]);}
    public function update(ActualizarUsuarioRequest$r,UserEloquentModel$usuario,RegistrarAuditoria$a):RedirectResponse{DB::transaction(function()use($r,$usuario,$a){$antes=['name'=>$usuario->name,'email'=>$usuario->email];$d=$r->safe()->except('password');if($r->filled('password'))$d['password']=$r->validated('password');$usuario->update($d);if($r->filled('password'))$this->revocarAccesos($usuario);$a->registrar('usuario.actualizado','usuario',$usuario->id,['antes'=>$antes,'despues'=>['name'=>$usuario->name,'email'=>$usuario->email],'password_actualizada'=>$r->filled('password')],$r);});return redirect()->route('usuarios.index')->with('success','Usuario actualizado.');}
    public function roles(ActualizarRolesUsuarioRequest$r,UserEloquentModel$usuario,RegistrarAuditoria$a):RedirectResponse{DB::transaction(function()use($r,$usuario,$a){DB::statement("SELECT pg_advisory_xact_lock(hashtext('autofix_admin_users'))");$bloqueado=UserEloquentModel::whereKey($usuario->id)->lockForUpdate()->firstOrFail();$anteriores=$bloqueado->getRoleNames();$roles=RoleEloquentModel::whereIn('id',$r->validated('role_ids'))->get();$nuevos=$roles->pluck('name');if($bloqueado->is($r->user())&&$anteriores->contains('Administrador')&&!$nuevos->contains('Administrador'))throw ValidationException::withMessages(['roles'=>'No puedes retirar tu propio rol de Administrador.']);if($bloqueado->activo&&$anteriores->contains('Administrador')&&!$nuevos->contains('Administrador')&&$this->administradoresActivos()<=1)throw ValidationException::withMessages(['roles'=>'Debe existir al menos otro administrador activo.']);$bloqueado->syncRoles($roles);$a->registrar('usuario.roles_actualizados','usuario',$bloqueado->id,['antes'=>$anteriores->all(),'despues'=>$nuevos->all()],$r);});return back()->with('success','Roles actualizados.');}
    public function estado(CambiarEstadoUsuarioRequest$r,UserEloquentModel$usuario,RegistrarAuditoria$a):RedirectResponse{DB::transaction(function()use($r,$usuario,$a){DB::statement("SELECT pg_advisory_xact_lock(hashtext('autofix_admin_users'))");$bloqueado=UserEloquentModel::whereKey($usuario->id)->lockForUpdate()->firstOrFail();$activo=(bool)$r->validated('activo');if($bloqueado->is($r->user())&&!$activo)throw ValidationException::withMessages(['activo'=>'No puedes desactivar tu propia cuenta.']);if(!$activo&&$bloqueado->activo&&$bloqueado->hasRole('Administrador')&&$this->administradoresActivos()<=1)throw ValidationException::withMessages(['activo'=>'Debe existir al menos otro administrador activo.']);$anterior=$bloqueado->activo;$bloqueado->update(['activo'=>$activo]);if(!$activo)$this->revocarAccesos($bloqueado);$a->registrar('usuario.estado_cambiado','usuario',$bloqueado->id,['anterior'=>$anterior,'nuevo'=>$activo],$r);});return back()->with('success','Estado del usuario actualizado.');}
    public function eliminar(Request$r,UserEloquentModel$usuario,RegistrarAuditoria$a):RedirectResponse{DB::transaction(function()use($r,$usuario,$a){if(DB::connection()->getDriverName()==='pgsql')DB::statement("SELECT pg_advisory_xact_lock(hashtext('autofix_admin_users'))");$bloqueado=UserEloquentModel::whereKey($usuario->id)->lockForUpdate()->firstOrFail();if($bloqueado->is($r->user()))throw ValidationException::withMessages(['usuario'=>'No puedes eliminar tu propia cuenta.']);if($bloqueado->activo&&$bloqueado->hasRole('Administrador')&&$this->administradoresActivos()<=1)throw ValidationException::withMessages(['usuario'=>'Debe existir al menos otro administrador activo.']);if(!$bloqueado->activo)throw ValidationException::withMessages(['usuario'=>'El usuario ya se encuentra inactivo.']);$bloqueado->update(['activo'=>false]);$this->revocarAccesos($bloqueado);$a->registrar('usuario.eliminado','usuario',$bloqueado->id,['activo_anterior'=>true,'nuevo'=>false,'metodo'=>'eliminacion_soft'],$r);});return back()->with('success','Usuario eliminado. Quedó inactivo y se conservó su registro.');}
    private function catalogoRoles(bool$incluirCliente=true){return RoleEloquentModel::where('guard_name','web')->when(!$incluirCliente,fn($q)=>$q->where('name','<>','Cliente'))->orderBy('name')->get(['id','name']);}
    private function administradoresActivos():int{return UserEloquentModel::where('activo',true)->role('Administrador')->count();}
    private function revocarAccesos(UserEloquentModel$usuario):void{DB::table('sessions')->where('user_id',$usuario->id)->delete();$usuario->tokens()->delete();$usuario->forceFill(['remember_token'=>null])->save();}
}
