<script setup lang="ts">
import { ref } from 'vue'
import { Head, Link, router } from '@inertiajs/vue3'
import { route } from 'ziggy-js'
import { usePermissions } from '../../composables/usePermissions'
interface Orden { id:string;numero:string;cliente:string;vehiculo:string;estado:string;recibidaEn:string;mecanicos:string[] }
const props=defineProps<{ordenes:{data:Orden[];prev_page_url:string|null;next_page_url:string|null;total:number};estado?:string}>();const filtro=ref(props.estado??'todos');const{can}=usePermissions();const estados=['todos','pendiente','en_diagnostico','en_reparacion','finalizada','entregada','cancelada'];function filtrar(){router.get(route('ordenes.index'),{estado:filtro.value==='todos'?undefined:filtro.value},{preserveState:true,replace:true})}
</script>
<template><Head title="Órdenes de trabajo"/><UDashboardPanel><template #header><UDashboardNavbar title="Órdenes de trabajo"><template #right><UButton v-if="can('ordenes.crear')" label="Nueva orden" icon="i-lucide-plus" @click="router.visit(route('ordenes.create'))"/></template></UDashboardNavbar></template><template #body><div class="flex flex-col gap-3 sm:flex-row"><USelect v-model="filtro" class="w-full sm:w-52" :items="estados"/><UButton label="Filtrar" @click="filtrar"/></div><ul v-if="ordenes.data.length" class="divide-y divide-default overflow-hidden rounded-lg border border-default bg-elevated"><li v-for="o in ordenes.data" :key="o.id"><Link :href="route('ordenes.show',o.id)" class="block p-4 transition hover:bg-default/50 focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-primary sm:p-5"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div class="min-w-0"><p class="text-sm font-semibold text-primary">{{o.numero}}</p><h2 class="font-semibold">{{o.vehiculo}} · {{o.cliente}}</h2><dl class="mt-3 grid gap-x-6 gap-y-2 text-sm md:grid-cols-2"><div><dt class="text-muted">Recibida</dt><dd>{{new Date(o.recibidaEn).toLocaleString('es-CO')}}</dd></div><div><dt class="text-muted">Mecánicos</dt><dd>{{o.mecanicos.join(', ')||'Sin asignar'}}</dd></div></dl></div><UBadge class="self-start sm:self-center" :color="o.estado==='cancelada'?'error':o.estado==='entregada'?'success':'primary'" variant="subtle">{{o.estado.replaceAll('_',' ')}}</UBadge></div></Link></li></ul><div v-else class="rounded-lg border border-default bg-elevated"><p class="py-10 text-center text-muted">No hay órdenes para mostrar.</p></div><div class="flex flex-wrap justify-end gap-2"><UButton label="Anterior" color="neutral" variant="outline" :disabled="!ordenes.prev_page_url" @click="ordenes.prev_page_url&&router.visit(ordenes.prev_page_url)"/><UButton label="Siguiente" color="neutral" variant="outline" :disabled="!ordenes.next_page_url" @click="ordenes.next_page_url&&router.visit(ordenes.next_page_url)"/></div></template></UDashboardPanel></template>
