<script setup lang="ts">
import { ref } from 'vue'
import { Head, Link, router } from '@inertiajs/vue3'
import { route } from 'ziggy-js'
import { usePermissions } from '../../composables/usePermissions'
interface Orden { id:string;numero:string;cliente:string;vehiculo:string;estado:string;recibidaEn:string;mecanicos:string[] }
const props=defineProps<{ordenes:{data:Orden[];prev_page_url:string|null;next_page_url:string|null;total:number};estado?:string}>();const filtro=ref(props.estado??'todos');const{can}=usePermissions();const estados=['todos','pendiente','en_diagnostico','en_reparacion','finalizada','entregada','cancelada'];function filtrar(){router.get(route('ordenes.index'),{estado:filtro.value==='todos'?undefined:filtro.value},{preserveState:true,replace:true})}
</script>
<template><Head title="Órdenes de trabajo"/><UDashboardPanel><template #header><UDashboardNavbar title="Órdenes de trabajo"><template #right><UButton v-if="can('ordenes.crear')" label="Nueva orden" icon="i-lucide-plus" @click="router.visit(route('ordenes.create'))"/></template></UDashboardNavbar></template><template #body><div class="flex gap-3"><USelect v-model="filtro" class="w-52" :items="estados"/><UButton label="Filtrar" @click="filtrar"/></div><div class="grid gap-4 lg:grid-cols-2"><Link v-for="o in ordenes.data" :key="o.id" :href="route('ordenes.show',o.id)"><UCard class="h-full transition hover:ring-2 hover:ring-primary/30"><div class="flex justify-between gap-3"><div><p class="text-sm font-semibold text-primary">{{o.numero}}</p><h2 class="font-semibold">{{o.vehiculo}} · {{o.cliente}}</h2></div><UBadge :color="o.estado==='cancelada'?'error':o.estado==='entregada'?'success':'primary'" variant="subtle">{{o.estado.replaceAll('_',' ')}}</UBadge></div><div class="mt-4 text-sm"><p class="text-muted">Recibida: {{new Date(o.recibidaEn).toLocaleString('es-CO')}}</p><p class="mt-2">Mecánicos: {{o.mecanicos.join(', ')||'Sin asignar'}}</p></div></UCard></Link><UCard v-if="!ordenes.data.length" class="lg:col-span-2"><p class="py-10 text-center text-muted">No hay órdenes para mostrar.</p></UCard></div><div class="flex justify-end gap-2"><UButton label="Anterior" color="neutral" variant="outline" :disabled="!ordenes.prev_page_url" @click="ordenes.prev_page_url&&router.visit(ordenes.prev_page_url)"/><UButton label="Siguiente" color="neutral" variant="outline" :disabled="!ordenes.next_page_url" @click="ordenes.next_page_url&&router.visit(ordenes.next_page_url)"/></div></template></UDashboardPanel></template>
