<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { Head, Link, router, usePage } from '@inertiajs/vue3'
import { route } from 'ziggy-js'
import { usePermissions } from '../../composables/usePermissions'

interface ServicioOrden {id:string;nombre:string;precio:string;estado:string;observaciones?:string}
interface Orden { id:string; numero:string; cliente:string; vehiculo:string; estado:string; fallaReportada:string; kilometraje?:number; servicios:ServicioOrden[]; mecanicoIds:string[]; mecanicos:string[]; diagnosticos:{id:string;version:number;diagnostico:string;pruebasRealizadas?:string;recomendaciones?:string;vigente:boolean;createdAt:string}[] }
interface Uso { id:string;codigo:string;nombre:string;unidad:string;cantidad:string;precioUnitario:string;revertido:boolean;createdAt:string }
interface Finanzas { servicios:string;repuestos:string;descuento:string;impuesto:string;total:string;pagado:string;saldo:string;estado:string;moneda:string }
interface Pago { id:string;numero:string;comprobante:string;monto:string;metodo:string;referencia?:string;estado:string;pagadoEn:string;motivoAnulacion?:string }
interface Factura { id:string;numero:string;total:string;emitidaEn:string }
interface DiagnosticoIa { id:string;estado:string;resumen?:string;riesgo?:string;circulacion?:string;especialidad?:string;mecanico?:string;revisada:boolean }
const props = defineProps<{ orden:Orden; mecanicos:{label:string;value:string}[]; repuestos:{label:string;value:string}[]; repuestosUsados:Uso[]; finanzas:Finanzas|null; pagos:Pago[]; factura:Factura|null; diagnosticoIa:DiagnosticoIa|null }>()
const { can, canAny } = usePermissions()
const errors = computed<Record<string,string>>(() => usePage().props.errors as Record<string,string>)
const asignacion = ref([...props.orden.mecanicoIds])
const diag = reactive({ diagnostico:'', pruebasRealizadas:'', recomendaciones:'' })
const consumo = reactive({ repuestoId:'', cantidad:'1.000', observaciones:'' })
const fechaLocal = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0,16)
const pago = reactive({ monto:'', metodo:'efectivo', referencia:'', observaciones:'', pagadoEn:fechaLocal() })
const facturacion = reactive({ descuento:'0.00', motivoDescuento:'', tasaImpuesto:'0.00', venceEn:'', observaciones:'' })
const procesando = ref(false)
const totalRepuestos = computed(() => props.repuestosUsados.filter(u => !u.revertido).reduce((total,u) => total + Number(u.cantidad) * Number(u.precioUnitario), 0))

function toggle(id:string, valor:boolean) { if(valor && !asignacion.value.includes(id)) asignacion.value.push(id); if(!valor) asignacion.value=asignacion.value.filter(x=>x!==id) }
function asignar() { router.patch(route('ordenes.asignar',props.orden.id),{mecanicoIds:asignacion.value},{preserveScroll:true}) }
function estado(nuevo:string) { const data:any={estado:nuevo}; if(nuevo==='cancelada'){const m=prompt('Motivo de cancelación');if(!m)return;data.motivo=m} if(confirm(`¿Cambiar la orden a ${nuevo.replaceAll('_',' ')}?`))router.patch(route('ordenes.estado',props.orden.id),data,{preserveScroll:true}) }
function estadoServicio(servicio:ServicioOrden,nuevo:string){const data:any={estado:nuevo};if(nuevo==='cancelado'){const motivo=prompt('Motivo de cancelación del servicio');if(!motivo)return;data.observaciones=motivo}router.patch(route('ordenes.servicios.estado',[props.orden.id,servicio.id]),data,{preserveScroll:true})}
function diagnosticar() { procesando.value=true;router.post(route('ordenes.diagnosticar',props.orden.id),diag,{preserveScroll:true,onSuccess:()=>Object.assign(diag,{diagnostico:'',pruebasRealizadas:'',recomendaciones:''}),onFinish:()=>procesando.value=false}) }
function usarRepuesto() { procesando.value=true;router.post(route('ordenes.repuestos.store',props.orden.id),consumo,{preserveScroll:true,onSuccess:()=>Object.assign(consumo,{repuestoId:'',cantidad:'1.000',observaciones:''}),onFinish:()=>procesando.value=false}) }
function revertir(uso:Uso) { const motivo=prompt('Motivo de la reversión');if(!motivo)return;router.post(route('ordenes.repuestos.revertir',uso.id),{motivo},{preserveScroll:true}) }
function registrarPago() { procesando.value=true;router.post(route('pagos.store',props.orden.id),{...pago,pagadoEn:new Date(pago.pagadoEn).toISOString()},{preserveScroll:true,onSuccess:()=>Object.assign(pago,{monto:'',metodo:'efectivo',referencia:'',observaciones:'',pagadoEn:fechaLocal()}),onFinish:()=>procesando.value=false}) }
function anularPago(item:Pago) { const motivo=prompt('Motivo de la anulación');if(!motivo)return;router.post(route('pagos.anular',item.id),{motivo},{preserveScroll:true}) }
function emitirFactura() { if(!confirm('¿Emitir la factura definitiva con estos valores?'))return;procesando.value=true;router.post(route('facturacion.store',props.orden.id),facturacion,{preserveScroll:true,onFinish:()=>procesando.value=false}) }
function dinero(valor:string|number) { return Number(valor).toLocaleString('es-CO',{minimumFractionDigits:2,maximumFractionDigits:2}) }
</script>

<template>
  <Head :title="orden.numero" />
  <UDashboardPanel>
    <template #header><UDashboardNavbar :title="orden.numero"><template #right><Link v-if="diagnosticoIa&&canAny(['ia.solicitar','ia.revisar'])" :href="route('ia.show',diagnosticoIa.id)"><UButton label="Ver IA" icon="i-lucide-brain-circuit" color="neutral" variant="outline"/></Link><Link v-if="can('citas.ver')" :href="route('citas.calendario')"><UButton label="Calendario" icon="i-lucide-calendar-days" color="neutral" variant="outline"/></Link><UBadge size="lg">{{orden.estado.replaceAll('_',' ')}}</UBadge></template></UDashboardNavbar></template>
    <template #body>
      <div class="grid gap-6 xl:grid-cols-3">
        <div class="space-y-6 xl:col-span-2">
          <UAlert v-if="errors.estado||errors.diagnostico||errors.servicio||errors.orden" color="error" icon="i-lucide-circle-alert" title="No se pudo completar la acción" :description="errors.estado||errors.diagnostico||errors.servicio||errors.orden"/>
          <UCard v-if="diagnosticoIa" :class="diagnosticoIa.estado==='descartada'?'border-error/25 bg-error/5':'border-primary/20 bg-primary/5'"><template #header><div class="flex items-center justify-between gap-3"><div><p class="font-mono text-xs uppercase tracking-wider text-primary">Diagnóstico preliminar IA</p><h2 class="mt-1 font-semibold">{{diagnosticoIa.estado==='descartada'?'Descartado por revisión humana':diagnosticoIa.revisada?'Revisado por mecánico':'Pendiente de revisión humana'}}</h2></div><UBadge variant="subtle">{{diagnosticoIa.estado.replaceAll('_',' ')}}</UBadge></div></template><p class="text-sm leading-6">{{diagnosticoIa.estado==='descartada'?'Esta sugerencia no debe utilizarse para decidir trabajos, repuestos o circulación.':diagnosticoIa.resumen}}</p><div v-if="diagnosticoIa.estado!=='descartada'" class="mt-3 flex flex-wrap gap-2"><UBadge v-if="diagnosticoIa.especialidad" color="primary" variant="subtle">{{diagnosticoIa.especialidad}}</UBadge><UBadge v-if="diagnosticoIa.mecanico" color="neutral" variant="outline">{{diagnosticoIa.mecanico}}</UBadge><UBadge v-if="diagnosticoIa.riesgo" color="warning" variant="subtle">Riesgo {{diagnosticoIa.riesgo}}</UBadge><UBadge v-if="diagnosticoIa.circulacion" color="neutral" variant="outline">Circulación {{diagnosticoIa.circulacion}}</UBadge></div></UCard>
          <UCard><template #header><h2 class="font-semibold">Vehículo y falla reportada</h2></template><p class="font-medium">{{orden.vehiculo}} · {{orden.cliente}}</p><p v-if="orden.kilometraje" class="text-sm text-muted">{{orden.kilometraje.toLocaleString('es-CO')}} km</p><p class="mt-4 whitespace-pre-wrap">{{orden.fallaReportada}}</p></UCard>
          <UCard><template #header><div><h2 class="font-semibold">Servicios</h2><p class="text-sm text-muted">Todos deben quedar completados o cancelados antes de finalizar.</p></div></template><div v-for="s in orden.servicios" :key="s.id" class="flex flex-col gap-3 border-b border-default py-3 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><span class="font-medium">{{s.nombre}}</span><UBadge :color="s.estado==='completado'?'success':s.estado==='cancelado'?'neutral':s.estado==='en_proceso'?'warning':'primary'" variant="subtle">{{s.estado.replaceAll('_',' ')}}</UBadge></div><p class="text-sm text-muted">$ {{dinero(s.precio)}}</p><p v-if="s.observaciones" class="mt-1 text-xs text-muted">{{s.observaciones}}</p></div><div v-if="can('ordenes.avanzar')&&['en_diagnostico','en_reparacion'].includes(orden.estado)&&!['completado','cancelado'].includes(s.estado)" class="flex flex-wrap gap-1"><UButton v-if="s.estado==='pendiente'" size="xs" color="neutral" variant="outline" label="Iniciar" @click="estadoServicio(s,'en_proceso')"/><UButton size="xs" color="success" variant="soft" label="Completar" @click="estadoServicio(s,'completado')"/><UButton size="xs" color="error" variant="ghost" label="Cancelar" @click="estadoServicio(s,'cancelado')"/></div></div></UCard>

          <UCard>
            <template #header><div class="flex items-center justify-between"><h2 class="font-semibold">Repuestos utilizados</h2><p class="text-sm font-medium">Total $ {{dinero(totalRepuestos)}}</p></div></template>
            <form v-if="can('inventario.consumir')&&['en_diagnostico','en_reparacion'].includes(orden.estado)" class="mb-5 grid gap-4 rounded-lg bg-elevated/50 p-4 sm:grid-cols-2" @submit.prevent="usarRepuesto">
              <UFormField label="Repuesto" required :error="errors.repuestoId"><USelect v-model="consumo.repuestoId" :items="repuestos" class="w-full" /></UFormField>
              <UFormField label="Cantidad" required :error="errors.cantidad"><UInput v-model="consumo.cantidad" type="number" min="0.001" step="0.001" class="w-full" /></UFormField>
              <UFormField class="sm:col-span-2" label="Observaciones"><UInput v-model="consumo.observaciones" class="w-full" /></UFormField>
              <div class="sm:col-span-2 text-right"><UButton type="submit" label="Descontar del inventario" :loading="procesando" /></div>
            </form>
            <div v-for="u in repuestosUsados" :key="u.id" class="flex flex-col gap-2 border-b border-default py-3 last:border-0 sm:flex-row sm:items-center sm:justify-between" :class="u.revertido?'opacity-55':''"><div><p class="font-medium" :class="u.revertido?'line-through':''">{{u.codigo}} · {{u.nombre}}</p><p class="text-sm text-muted">{{u.cantidad}} {{u.unidad}} · $ {{dinero(u.precioUnitario)}} c/u</p></div><div class="flex items-center gap-2"><UBadge v-if="u.revertido" color="neutral">Revertido</UBadge><UButton v-else-if="canAny(['inventario.gestionar','inventario.consumir'])" size="xs" color="neutral" variant="ghost" label="Revertir" @click="revertir(u)" /></div></div>
            <p v-if="!repuestosUsados.length" class="py-4 text-center text-muted">Aún no se han utilizado repuestos.</p>
          </UCard>

          <UCard v-if="finanzas">
            <template #header><div class="flex flex-wrap items-center justify-between gap-2"><div><h2 class="font-semibold">Estado financiero</h2><p class="text-sm text-muted">Valores expresados en COP</p></div><UBadge :color="finanzas.estado==='pagado'?'success':finanzas.estado==='parcial'?'warning':'neutral'">{{finanzas.estado}}</UBadge></div></template>
            <div class="grid gap-3 sm:grid-cols-4"><div><p class="text-xs text-muted">Servicios</p><p class="font-medium">$ {{dinero(finanzas.servicios)}}</p></div><div><p class="text-xs text-muted">Repuestos</p><p class="font-medium">$ {{dinero(finanzas.repuestos)}}</p></div><div><p class="text-xs text-muted">Pagado</p><p class="font-medium text-success">$ {{dinero(finanzas.pagado)}}</p></div><div><p class="text-xs text-muted">Saldo</p><p class="text-xl font-semibold">$ {{dinero(finanzas.saldo)}}</p></div><div v-if="Number(finanzas.descuento)>0"><p class="text-xs text-muted">Descuento facturado</p><p class="font-medium">-$ {{dinero(finanzas.descuento)}}</p></div><div v-if="Number(finanzas.impuesto)>0"><p class="text-xs text-muted">Impuesto facturado</p><p class="font-medium">$ {{dinero(finanzas.impuesto)}}</p></div><div><p class="text-xs text-muted">Total vigente</p><p class="font-semibold">$ {{dinero(finanzas.total)}}</p></div></div>
            <form v-if="can('pagos.registrar')&&orden.estado!=='cancelada'&&Number(finanzas.saldo)>0" class="mt-5 grid gap-4 rounded-lg bg-elevated/50 p-4 sm:grid-cols-2" @submit.prevent="registrarPago"><UFormField label="Monto" required :error="errors.monto"><UInput v-model="pago.monto" type="number" min="0.01" :max="finanzas.saldo" step="0.01" class="w-full" /></UFormField><UFormField label="Método" required><USelect v-model="pago.metodo" :items="[{label:'Efectivo',value:'efectivo'},{label:'Tarjeta',value:'tarjeta'},{label:'Transferencia',value:'transferencia'},{label:'Otro',value:'otro'}]" class="w-full" /></UFormField><UFormField label="Fecha del pago" required><UInput v-model="pago.pagadoEn" type="datetime-local" class="w-full" /></UFormField><UFormField label="Referencia"><UInput v-model="pago.referencia" class="w-full" /></UFormField><UFormField class="sm:col-span-2" label="Observaciones"><UInput v-model="pago.observaciones" class="w-full" /></UFormField><div class="sm:col-span-2 text-right"><UButton type="submit" label="Registrar pago" :loading="procesando" /></div></form>
            <div class="mt-5"><h3 class="mb-2 text-sm font-semibold">Historial de pagos</h3><div v-for="item in pagos" :key="item.id" class="flex flex-col gap-2 border-b border-default py-3 last:border-0 sm:flex-row sm:items-center sm:justify-between" :class="item.estado==='anulado'?'opacity-55':''"><div><p class="font-medium" :class="item.estado==='anulado'?'line-through':''">{{item.numero}} · $ {{dinero(item.monto)}}</p><p class="text-xs text-muted">{{item.metodo}} · {{new Date(item.pagadoEn).toLocaleString('es-CO')}} · {{item.comprobante}}</p><p v-if="item.referencia" class="text-xs text-muted">Ref. {{item.referencia}}</p></div><div class="flex items-center gap-2"><UBadge :color="item.estado==='registrado'?'success':'neutral'">{{item.estado}}</UBadge><UButton v-if="can('pagos.anular')&&item.estado==='registrado'" size="xs" color="error" variant="ghost" label="Anular" @click="anularPago(item)" /></div></div><p v-if="!pagos.length" class="py-3 text-center text-muted">Sin pagos registrados.</p></div>
          </UCard>

          <UCard v-if="canAny(['facturas.ver','facturas.crear'])&&['finalizada','entregada'].includes(orden.estado)">
            <template #header><h2 class="font-semibold">Facturación definitiva</h2></template>
            <div v-if="factura" class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-lg font-semibold">{{factura.numero}}</p><p class="text-sm text-muted">Emitida {{new Date(factura.emitidaEn).toLocaleString('es-CO')}} · Total $ {{dinero(factura.total)}} COP</p></div><Link v-if="can('facturas.ver')" :href="route('facturacion.show',factura.id)"><UButton label="Ver factura" icon="i-lucide-receipt-text"/></Link></div>
            <form v-else-if="can('facturas.crear')" class="grid gap-4 sm:grid-cols-2" @submit.prevent="emitirFactura"><UFormField label="Descuento" required :error="errors.descuento"><UInput v-model="facturacion.descuento" type="number" min="0" step="0.01" class="w-full" :disabled="!can('descuentos.autorizar')"/></UFormField><UFormField label="Impuesto (%)" required :error="errors.tasa_impuesto"><UInput v-model="facturacion.tasaImpuesto" type="number" min="0" max="100" step="0.01" class="w-full"/></UFormField><UFormField v-if="can('descuentos.autorizar')&&Number(facturacion.descuento)>0" label="Motivo del descuento" required :error="errors.motivo_descuento" class="sm:col-span-2"><UInput v-model="facturacion.motivoDescuento" class="w-full" placeholder="Justificación de la autorización"/></UFormField><UFormField label="Fecha de vencimiento"><UInput v-model="facturacion.venceEn" type="date" class="w-full"/></UFormField><UFormField label="Observaciones"><UInput v-model="facturacion.observaciones" class="w-full"/></UFormField><div class="sm:col-span-2"><UAlert color="warning" variant="subtle" :title="can('descuentos.autorizar')?'La factura congela los conceptos y valores actuales de la orden.':'La factura se emitirá sin descuento; solo Administración puede autorizar descuentos.'"/><div class="mt-3 text-right"><UButton type="submit" label="Emitir factura" icon="i-lucide-file-check" :loading="procesando"/></div></div></form>
          </UCard>

          <UCard><template #header><h2 class="font-semibold">Diagnóstico técnico</h2></template><form v-if="can('diagnosticos.registrar')&&['en_diagnostico','en_reparacion'].includes(orden.estado)" class="space-y-4" @submit.prevent="diagnosticar"><UFormField label="Diagnóstico" required :error="errors.diagnostico"><UTextarea v-model="diag.diagnostico" class="w-full" :rows="5" /></UFormField><UFormField label="Pruebas realizadas"><UTextarea v-model="diag.pruebasRealizadas" class="w-full" /></UFormField><UFormField label="Recomendaciones"><UTextarea v-model="diag.recomendaciones" class="w-full" /></UFormField><div class="text-right"><UButton type="submit" label="Registrar nueva versión" :loading="procesando" /></div></form><div v-for="d in orden.diagnosticos" :key="d.id" class="mt-4 rounded-lg border border-default p-4"><div class="flex justify-between"><p class="font-medium">Versión {{d.version}}</p><UBadge :color="d.vigente?'success':'neutral'">{{d.vigente?'Vigente':'Anterior'}}</UBadge></div><p class="mt-3 whitespace-pre-wrap">{{d.diagnostico}}</p><p v-if="d.pruebasRealizadas" class="mt-2 text-sm"><strong>Pruebas:</strong> {{d.pruebasRealizadas}}</p><p v-if="d.recomendaciones" class="mt-2 text-sm"><strong>Recomendaciones:</strong> {{d.recomendaciones}}</p></div><p v-if="!orden.diagnosticos.length" class="mt-4 text-center text-muted">Sin diagnósticos registrados.</p></UCard>
        </div>

        <aside class="space-y-6">
          <UCard v-if="canAny(['ordenes.avanzar','ordenes.cancelar'])"><template #header><h2 class="font-semibold">Cambiar estado</h2></template><div class="grid gap-2"><UButton v-if="can('ordenes.avanzar')&&orden.estado==='pendiente'" label="Iniciar diagnóstico" @click="estado('en_diagnostico')" /><UButton v-if="can('ordenes.avanzar')&&orden.estado==='en_diagnostico'" label="Iniciar reparación" @click="estado('en_reparacion')" /><UButton v-if="can('ordenes.avanzar')&&orden.estado==='en_reparacion'" label="Finalizar orden" @click="estado('finalizada')" /><UButton v-if="can('ordenes.avanzar')&&orden.estado==='finalizada'" label="Marcar entregada" @click="estado('entregada')" /><UButton v-if="can('ordenes.cancelar')&&!['entregada','cancelada','finalizada'].includes(orden.estado)" color="error" variant="soft" label="Cancelar orden" @click="estado('cancelada')" /></div></UCard>
          <UCard v-if="can('ordenes.asignar')"><template #header><h2 class="font-semibold">Mecánicos asignados</h2></template><div class="space-y-3"><UCheckbox v-for="m in mecanicos" :key="m.value" :model-value="asignacion.includes(m.value)" :label="m.label" @update:model-value="toggle(m.value,Boolean($event))" /></div><template #footer><div class="text-right"><UButton label="Guardar asignación" size="sm" @click="asignar" /></div></template></UCard>
          <UCard v-else><template #header><h2 class="font-semibold">Mecánicos</h2></template><p v-for="m in orden.mecanicos" :key="m">{{m}}</p><p v-if="!orden.mecanicos.length" class="text-muted">Sin asignación.</p></UCard>
        </aside>
      </div>
    </template>
  </UDashboardPanel>
</template>
