<?php
namespace Src\Inventario\Application\Controllers;
use App\Http\Controllers\Controller;use Brick\Math\BigDecimal;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;use Illuminate\Validation\ValidationException;use Inertia\Inertia;use Inertia\Response;use Src\Auditoria\Application\Services\RegistrarAuditoria;use Src\Inventario\Application\Services\RegistrarMovimientoInventario;use Src\Inventario\Infrastructure\Models\CategoriaRepuestoEloquentModel;use Src\Inventario\Infrastructure\Models\MovimientoInventarioEloquentModel;use Src\Inventario\Infrastructure\Models\OrdenRepuestoEloquentModel;use Src\Inventario\Infrastructure\Models\ProveedorEloquentModel;use Src\Inventario\Infrastructure\Models\RepuestoEloquentModel;use Src\Inventario\Infrastructure\Requests\ActualizarRepuestoRequest;use Src\Inventario\Infrastructure\Requests\GuardarRepuestoRequest;use Src\Inventario\Infrastructure\Requests\RegistrarMovimientoRequest;use Src\Inventario\Infrastructure\Requests\UsarRepuestoOrdenRequest;use Src\OrdenTrabajo\Infrastructure\Models\OrdenTrabajoEloquentModel;
use Src\Pago\Application\Services\CalculadorTotalOrden;
class InventarioWebController extends Controller
{
    public function index(Request$request):Response{$buscar=trim((string)$request->input('buscar'));$estado=$request->input('estado');$categoria=$request->input('categoria');$proveedor=$request->input('proveedor');$bajo=$request->boolean('bajo');$repuestos=RepuestoEloquentModel::with(['categoria:id,nombre','proveedor:id,nombre'])->when($buscar,fn($q)=>$q->where(fn($s)=>$s->where('codigo','ilike',"%{$buscar}%")->orWhere('nombre','ilike',"%{$buscar}%")))->when($estado,fn($q)=>$q->where('estado',$estado))->when($categoria,fn($q)=>$q->where('categoria_id',$categoria))->when($proveedor,fn($q)=>$q->where('proveedor_id',$proveedor))->when($bajo,fn($q)=>$q->whereColumn('stock_actual','<=','stock_minimo'))->orderBy('nombre')->paginate(15)->withQueryString();$movimientos=MovimientoInventarioEloquentModel::with('repuesto:id,codigo,nombre')->latest('created_at')->limit(20)->get();$catalogos=$this->catalogosDatos();return Inertia::render('Inventario/index',[...$catalogos,'vista'=>$request->route('vista')??'catalogo','repuestos'=>$repuestos,'movimientos'=>$movimientos,'filtros'=>['buscar'=>$buscar,'estado'=>$estado??'','categoria'=>$categoria??'','proveedor'=>$proveedor??'','bajo'=>$bajo],'stats'=>['total'=>RepuestoEloquentModel::count(),'bajos'=>RepuestoEloquentModel::where('estado','activo')->whereColumn('stock_actual','<=','stock_minimo')->count(),'agotados'=>RepuestoEloquentModel::where('estado','activo')->where('stock_actual',0)->count()]]);}
    public function catalogos():Response{return Inertia::render('Inventario/catalogos',$this->catalogosDatos());}
    public function show(Request$r,RepuestoEloquentModel$p):Response{$f=$r->validate(['tipo'=>'nullable|in:entrada,salida,ajuste,reversion','desde'=>'nullable|date','hasta'=>'nullable|date|after_or_equal:desde']);$tipo=$f['tipo']??null;$desde=$f['desde']??null;$hasta=$f['hasta']??null;$p->load(['categoria','proveedor']);$movimientos=MovimientoInventarioEloquentModel::with(['orden:id,numero','usuario:id,name','origen:id,tipo,cantidad'])->where('repuesto_id',$p->id)->when($tipo,fn($q)=>$q->where('tipo',$tipo))->when($desde,fn($q)=>$q->whereDate('created_at','>=',$desde))->when($hasta,fn($q)=>$q->whereDate('created_at','<=',$hasta))->latest('created_at')->paginate(25)->withQueryString();return Inertia::render('Inventario/show',['repuesto'=>$p,'movimientos'=>$movimientos,'filtros'=>['tipo'=>$tipo??'','desde'=>$desde??'','hasta'=>$hasta??'']]);}
    public function edit(RepuestoEloquentModel$p):Response{$p->load(['categoria','proveedor']);return Inertia::render('Inventario/form',['repuesto'=>$p,...$this->catalogosDatos()]);}
    public function storeCategoria(Request$r,RegistrarAuditoria$a):RedirectResponse{abort_unless($r->user()->can('inventario.gestionar'),403);$d=$r->validate(['nombre'=>'required|string|max:120|unique:categorias_repuesto,nombre','descripcion'=>'nullable|string|max:1000']);$c=CategoriaRepuestoEloquentModel::create([...$d,'estado'=>'activo','creado_por'=>$r->user()->id,'actualizado_por'=>$r->user()->id]);$a->registrar('categoria_repuesto.creada','categoria_repuesto',$c->id,[],$r);return back()->with('success','Categoría creada.');}
    public function updateCategoria(Request$r,CategoriaRepuestoEloquentModel$c,RegistrarAuditoria$a):RedirectResponse{abort_unless($r->user()->can('inventario.gestionar'),403);$d=$r->validate(['nombre'=>['required','string','max:120',Rule::unique('categorias_repuesto')->ignore($c->id)],'descripcion'=>'nullable|string|max:1000']);$antes=$c->only(['nombre','descripcion']);$c->update([...$d,'actualizado_por'=>$r->user()->id]);$a->registrar('categoria_repuesto.actualizada','categoria_repuesto',$c->id,['antes'=>$antes,'despues'=>$c->only(['nombre','descripcion'])],$r);return back()->with('success','Categoría actualizada.');}
    public function estadoCategoria(Request$r,CategoriaRepuestoEloquentModel$c,RegistrarAuditoria$a):RedirectResponse{$this->cambiarEstadoCatalogo($r,$c,$a,'categoria_repuesto');return back()->with('success','Estado de la categoría actualizado.');}
    public function storeProveedor(Request$r,RegistrarAuditoria$a):RedirectResponse{abort_unless($r->user()->can('inventario.gestionar'),403);$d=$r->validate(['documento'=>'required|string|max:40|unique:proveedores,documento','nombre'=>'required|string|max:180','contacto'=>'nullable|string|max:120','telefono'=>'nullable|string|max:30','email'=>'nullable|email|max:255']);$p=ProveedorEloquentModel::create([...$d,'estado'=>'activo','creado_por'=>$r->user()->id,'actualizado_por'=>$r->user()->id]);$a->registrar('proveedor.creado','proveedor',$p->id,[],$r);return back()->with('success','Proveedor creado.');}
    public function updateProveedor(Request$r,ProveedorEloquentModel$proveedor,RegistrarAuditoria$a):RedirectResponse{abort_unless($r->user()->can('inventario.gestionar'),403);$d=$r->validate(['documento'=>['required','string','max:40',Rule::unique('proveedores')->ignore($proveedor->id)],'nombre'=>'required|string|max:180','contacto'=>'nullable|string|max:120','telefono'=>'nullable|string|max:30','email'=>'nullable|email|max:255']);$antes=$proveedor->only(['documento','nombre','contacto','telefono','email']);$proveedor->update([...$d,'actualizado_por'=>$r->user()->id]);$a->registrar('proveedor.actualizado','proveedor',$proveedor->id,['antes'=>$antes,'despues'=>$proveedor->only(array_keys($antes))],$r);return back()->with('success','Proveedor actualizado.');}
    public function estadoProveedor(Request$r,ProveedorEloquentModel$proveedor,RegistrarAuditoria$a):RedirectResponse{$this->cambiarEstadoCatalogo($r,$proveedor,$a,'proveedor');return back()->with('success','Estado del proveedor actualizado.');}
    public function storeRepuesto(GuardarRepuestoRequest$r,RegistrarAuditoria$a):RedirectResponse{$p=RepuestoEloquentModel::create([...$r->validated(),'estado'=>'activo','creado_por'=>$r->user()->id,'actualizado_por'=>$r->user()->id]);$a->registrar('repuesto.creado','repuesto',$p->id,[],$r);return back()->with('success','Repuesto creado. Registra una entrada para aumentar su stock.');}
    public function updateRepuesto(ActualizarRepuestoRequest$r,RepuestoEloquentModel$p,RegistrarAuditoria$a):RedirectResponse{$d=$r->validated();if($p->unidad!==$d['unidad']&&MovimientoInventarioEloquentModel::where('repuesto_id',$p->id)->exists())throw ValidationException::withMessages(['unidad'=>'No se puede cambiar la unidad porque el repuesto ya tiene movimientos.']);$antes=$p->only(array_keys($d));$p->update([...$d,'actualizado_por'=>$r->user()->id]);$a->registrar('repuesto.actualizado','repuesto',$p->id,['antes'=>$antes,'despues'=>$p->only(array_keys($d))],$r);return redirect()->route('inventario.repuestos.show',$p)->with('success','Repuesto actualizado.');}
    public function movimiento(RegistrarMovimientoRequest$r,RegistrarMovimientoInventario$s,RegistrarAuditoria$a):RedirectResponse{$m=$s->registrar($r->validated('repuesto_id'),(string)$r->validated('cantidad'),$r->validated('tipo'),$r->validated('motivo'),$r->user()->id,null,$r->validated('costo_unitario'));$a->registrar('inventario.movimiento','movimiento_inventario',$m->id,['tipo'=>$m->tipo,'cantidad'=>$m->cantidad],$r);return back()->with('success','Movimiento registrado.');}
    public function estado(Request$r,RepuestoEloquentModel$p,RegistrarAuditoria$a):RedirectResponse{abort_unless($r->user()->can('inventario.gestionar'),403);$d=$r->validate(['estado'=>'required|in:activo,inactivo,archivado']);$anterior=$p->estado;$p->update(['estado'=>$d['estado'],'actualizado_por'=>$r->user()->id]);$a->registrar('repuesto.estado_cambiado','repuesto',$p->id,['anterior'=>$anterior,'nuevo'=>$p->estado],$r);return back()->with('success','Estado del repuesto actualizado.');}
    public function usar(UsarRepuestoOrdenRequest$r,OrdenTrabajoEloquentModel$orden,RegistrarMovimientoInventario$s,RegistrarAuditoria$a):RedirectResponse{$this->autorizarOrden($r,$orden);$uso=DB::transaction(function()use($r,$orden,$s){$bloqueada=OrdenTrabajoEloquentModel::whereKey($orden->id)->lockForUpdate()->firstOrFail();if(!in_array($bloqueada->estado,['en_diagnostico','en_reparacion'],true))throw ValidationException::withMessages(['orden'=>'La orden no permite consumir repuestos en su estado actual.']);$p=RepuestoEloquentModel::whereKey($r->validated('repuesto_id'))->where('estado','activo')->lockForUpdate()->firstOrFail();$cantidad=(string)BigDecimal::of((string)$r->validated('cantidad'))->negated();$m=$s->registrar($p->id,$cantidad,'salida','Uso en orden '.$bloqueada->numero.($r->validated('observaciones')?': '.$r->validated('observaciones'):''),$r->user()->id,$bloqueada->id,$p->costo_referencia);return OrdenRepuestoEloquentModel::create(['orden_id'=>$bloqueada->id,'repuesto_id'=>$p->id,'cantidad'=>$r->validated('cantidad'),'precio_unitario'=>$p->precio_venta,'movimiento_salida_id'=>$m->id,'registrado_por'=>$r->user()->id]);});$a->registrar('orden.repuesto_usado','orden_repuesto',$uso->id,[],$r);return back()->with('success','Repuesto descontado del inventario.');}
    public function revertir(Request$r,OrdenRepuestoEloquentModel$uso,RegistrarMovimientoInventario$s,CalculadorTotalOrden$calculador,RegistrarAuditoria$a):RedirectResponse{abort_unless($r->user()->can('inventario.gestionar')||$r->user()->can('inventario.consumir'),403);$orden=OrdenTrabajoEloquentModel::findOrFail($uso->orden_id);$this->autorizarOrden($r,$orden);$r->validate(['motivo'=>'required|string|min:5|max:1000']);DB::transaction(function()use($r,$uso,$s,$calculador){OrdenTrabajoEloquentModel::whereKey($uso->orden_id)->lockForUpdate()->firstOrFail();if(DB::table('facturas_orden')->where('orden_id',$uso->orden_id)->where('estado','emitida')->exists())throw \Illuminate\Validation\ValidationException::withMessages(['movimiento'=>'No se puede modificar una orden con factura vigente.']);$bloqueado=OrdenRepuestoEloquentModel::whereKey($uso->id)->lockForUpdate()->firstOrFail();if($bloqueado->revertido_en)throw \Illuminate\Validation\ValidationException::withMessages(['movimiento'=>'Este uso ya fue revertido.']);$resumen=$calculador->calcular($bloqueado->orden_id);$reduccion=BigDecimal::of($bloqueado->cantidad)->multipliedBy(BigDecimal::of($bloqueado->precio_unitario));if(BigDecimal::of($resumen['total'])->minus($reduccion)->isLessThan(BigDecimal::of($resumen['pagado'])))throw \Illuminate\Validation\ValidationException::withMessages(['movimiento'=>'Primero anula los pagos que excederían el nuevo total de la orden.']);$origen=MovimientoInventarioEloquentModel::findOrFail($bloqueado->movimiento_salida_id);$s->revertir($origen,$r->input('motivo'),$r->user()->id);$bloqueado->update(['revertido_en'=>now(),'revertido_por'=>$r->user()->id]);});$a->registrar('orden.repuesto_revertido','orden_repuesto',$uso->id,[],$r);return back()->with('success','Se creó el movimiento compensatorio.');}
    private function autorizarOrden(Request$r,OrdenTrabajoEloquentModel$o):void{abort_unless(OrdenTrabajoEloquentModel::whereKey($o->id)->visiblePara($r->user())->exists(),403);}
    private function catalogosDatos():array{return['categorias'=>CategoriaRepuestoEloquentModel::orderBy('nombre')->get(['id','nombre','descripcion','estado']),'proveedores'=>ProveedorEloquentModel::orderBy('nombre')->get(['id','documento','nombre','contacto','telefono','email','estado'])];}
    private function cambiarEstadoCatalogo(Request$r,$modelo,RegistrarAuditoria$a,string$tipo):void{abort_unless($r->user()->can('inventario.gestionar'),403);$d=$r->validate(['estado'=>'required|in:activo,inactivo,archivado']);$anterior=$modelo->estado;$modelo->update(['estado'=>$d['estado'],'actualizado_por'=>$r->user()->id]);$a->registrar($tipo.'.estado_cambiado',$tipo,$modelo->id,['anterior'=>$anterior,'nuevo'=>$modelo->estado],$r);}
}
