<?php
namespace Src\AsistenteIA\Infrastructure\Requests;
use Illuminate\Foundation\Http\FormRequest;use Illuminate\Support\Str;use Illuminate\Validation\Rule;use Src\Vehiculo\Infrastructure\Models\VehiculoEloquentModel;
class SolicitarDiagnosticoIaRequest extends FormRequest
{
    public function authorize():bool{return $this->user()?->can('ia.solicitar')??false;}
    protected function prepareForValidation():void{$campos=['categoriaFalla','sintomaPrincipal','momentoOcurre','frecuencia','tiempoDesdeInicio','senales','lucesTablero','perdidaPotenciaArranque','reparacionesRecientes','observaciones'];$d=['cliente_id'=>$this->input('clienteId'),'vehiculo_id'=>$this->input('vehiculoId'),'puede_circular'=>$this->input('puedeCircular'),'urgencia_percibida'=>$this->input('urgenciaPercibida')];foreach($campos as$c)$d[Str::snake($c)]=trim(preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u','',(string)$this->input($c)));$this->merge($d);}
    public function rules():array{return['cliente_id'=>['required','uuid',Rule::exists('clientes','id')->where('estado','activo')],'vehiculo_id'=>['required','uuid',Rule::exists('vehiculos','id')->where('estado','activo')],'kilometraje'=>['required','integer','min:0','max:9999999'],'categoria_falla'=>['required','string','max:80'],'sintoma_principal'=>['required','string','min:10','max:1500'],'momento_ocurre'=>['required','string','max:500'],'frecuencia'=>['required','string','max:200'],'tiempo_desde_inicio'=>['required','string','max:200'],'senales'=>['nullable','string','max:1000'],'luces_tablero'=>['nullable','string','max:500'],'perdida_potencia_arranque'=>['nullable','string','max:500'],'puede_circular'=>['required',Rule::in(['si','con_dificultad','no'])],'urgencia_percibida'=>['required',Rule::in(['baja','media','alta','critica'])],'reparaciones_recientes'=>['nullable','string','max:1000'],'observaciones'=>['nullable','string','max:1500']];}
    public function after():array{return[function($v){if($this->input('cliente_id')&&$this->input('vehiculo_id')&&!VehiculoEloquentModel::whereKey($this->input('vehiculo_id'))->where('cliente_id',$this->input('cliente_id'))->exists())$v->errors()->add('vehiculoId','El vehículo no pertenece al cliente.');}];}
}
