<script setup lang="ts">
import { ref } from 'vue'
import { Head, Link, router } from '@inertiajs/vue3'
import { route } from 'ziggy-js'
interface Factura{id:string;numero:string;cliente_nombre:string;cliente_documento:string;vehiculo_placa:string;subtotal:string;descuento:string;impuesto:string;total:string;moneda:string;estado:string;emitida_en:string;orden:{id:string;numero:string}}
interface Pagina<T>{data:T[];links:{url:string|null;label:string;active:boolean}[];total:number}
const props=defineProps<{facturas:Pagina<Factura>;buscar:string}>();const busqueda=ref(props.buscar)
function buscar(){router.get(route('facturacion.index'),{buscar:busqueda.value},{preserveState:true})}
function dinero(valor:string){return Number(valor).toLocaleString('es-CO',{minimumFractionDigits:2,maximumFractionDigits:2})}
</script>
<template><Head title="Facturación"/><UDashboardPanel><template #header><UDashboardNavbar title="Facturación definitiva"><template #leading><UDashboardSidebarCollapse/></template></UDashboardNavbar></template><template #body><div class="space-y-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm text-muted">Comprobantes emitidos desde órdenes finalizadas</p><p class="text-3xl font-semibold">{{facturas.total}} facturas</p></div><form class="flex gap-2" @submit.prevent="buscar"><UInput v-model="busqueda" icon="i-lucide-search" placeholder="Factura, orden, cliente o documento" class="w-full sm:w-80"/><UButton type="submit" label="Buscar"/></form></div><UAlert icon="i-lucide-info" color="neutral" variant="subtle" title="Las facturas nuevas se emiten desde el detalle de una orden finalizada o entregada."/><div class="space-y-3"><UCard v-for="f in facturas.data" :key="f.id"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><p class="font-semibold">{{f.numero}}</p><UBadge :color="f.estado==='emitida'?'success':'neutral'">{{f.estado}}</UBadge></div><p class="mt-1">{{f.cliente_nombre}} · {{f.cliente_documento}}</p><p class="text-sm text-muted">{{f.orden.numero}} · {{f.vehiculo_placa}} · {{new Date(f.emitida_en).toLocaleString('es-CO')}}</p></div><div class="text-left sm:text-right"><p class="text-2xl font-semibold" :class="f.estado==='anulada'?'line-through text-muted':''">$ {{dinero(f.total)}}</p><p class="text-xs text-muted">{{f.moneda}} · impuesto $ {{dinero(f.impuesto)}}</p><Link :href="route('facturacion.show',f.id)"><UButton class="mt-2" size="sm" color="neutral" variant="outline" label="Ver detalle"/></Link></div></div></UCard><UCard v-if="!facturas.data.length"><p class="py-8 text-center text-muted">No se encontraron facturas definitivas.</p></UCard></div><div class="flex flex-wrap gap-2"><Link v-for="link in facturas.links" :key="link.label" :href="link.url||''" preserve-scroll><UButton :disabled="!link.url" :variant="link.active?'solid':'outline'" color="neutral" size="sm"><span v-html="link.label"/></UButton></Link></div></div></template></UDashboardPanel></template>
