<script setup lang="ts">
import { reactive } from 'vue'
import { Head, Link, router } from '@inertiajs/vue3'
import { route } from 'ziggy-js'
import { usePermissions } from '../../composables/usePermissions'
interface Consulta{id:string;orden?:string;estadoOrden?:string;cliente:string;vehiculo:string;estado:string;prioridad:string;riesgo?:string;especialidad?:string;mecanico?:string;simulada:boolean;createdAt:string;updatedAt:string}
const props=defineProps<{consultas:{data:Consulta[];prev_page_url:string|null;next_page_url:string|null;from?:number;to?:number;total:number};filtros:{buscar:string;estado:string;prioridad:string;simulada:string;porPagina:number};stats:{total:number;pendientes:number;confirmadas:number;modificadas:number}}>()
const{can}=usePermissions();const filtros=reactive({...props.filtros})
function aplicar(){router.get(route('ia.index'),{buscar:filtros.buscar||undefined,estado:filtros.estado==='todos'?undefined:filtros.estado,prioridad:filtros.prioridad==='todas'?undefined:filtros.prioridad,simulada:filtros.simulada==='todas'?undefined:filtros.simulada,porPagina:filtros.porPagina},{preserveState:true,replace:true})}
function limpiar(){Object.assign(filtros,{buscar:'',estado:'todos',prioridad:'todas',simulada:'todas',porPagina:25});aplicar()}
function colorPrioridad(valor:string):'error'|'warning'|'success'|'primary'{return['alta','critica'].includes(valor)?'error':valor==='media'?'warning':valor==='baja'?'success':'primary'}
</script>
<template><Head title="Diagnósticos IA"/><UDashboardPanel><template #header><UDashboardNavbar title="Diagnósticos IA"><template #right><UButton v-if="can('ia.solicitar')" label="Nuevo diagnóstico" icon="i-lucide-sparkles" @click="router.visit(route('ia.create'))"/></template></UDashboardNavbar></template><template #body><div class="space-y-5">
  <UAlert title="Centro inteligente del taller" description="Cada resultado es preliminar, conserva su versión original y requiere revisión de un mecánico autorizado antes de continuar la reparación." color="warning" icon="i-lucide-triangle-alert"/>
  <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><UCard><p class="text-xs uppercase text-muted">Diagnósticos</p><p class="mt-1 font-mono text-3xl font-bold">{{stats.total}}</p></UCard><UCard class="border-warning/20 bg-warning/5"><p class="text-xs uppercase text-warning">Pendientes de revisión</p><p class="mt-1 font-mono text-3xl font-bold">{{stats.pendientes}}</p></UCard><UCard class="border-success/20 bg-success/5"><p class="text-xs uppercase text-success">Confirmados</p><p class="mt-1 font-mono text-3xl font-bold">{{stats.confirmadas}}</p></UCard><UCard class="border-primary/20 bg-primary/5"><p class="text-xs uppercase text-primary">Modificados</p><p class="mt-1 font-mono text-3xl font-bold">{{stats.modificadas}}</p></UCard></div>
  <form class="grid gap-3 rounded-xl border border-default bg-elevated/65 p-4 md:grid-cols-2 xl:grid-cols-[minmax(14rem,1fr)_12rem_12rem_12rem_7rem_auto_auto]" @submit.prevent="aplicar"><UInput v-model="filtros.buscar" icon="i-lucide-search" placeholder="Orden, cliente, placa o vehículo"/><USelect v-model="filtros.estado" :items="[{label:'Todos los estados',value:'todos'},...['generada','en_revision','confirmada','modificada','descartada','cerrada'].map(value=>({label:value.replaceAll('_',' '),value}))]"/><USelect v-model="filtros.prioridad" :items="[{label:'Todas las prioridades',value:'todas'},...['baja','media','alta','critica'].map(value=>({label:value,value}))]"/><USelect v-model="filtros.simulada" :items="[{label:'Real o simulado',value:'todas'},{label:'Diagnóstico real',value:'false'},{label:'Simulado',value:'true'}]"/><USelect v-model="filtros.porPagina" :items="[10,25,50,100]"/><UButton type="submit" label="Filtrar" icon="i-lucide-list-filter"/><UButton type="button" label="Limpiar" color="neutral" variant="ghost" @click="limpiar"/></form>
  <div class="overflow-x-auto rounded-xl border border-default bg-elevated/70"><table class="w-full min-w-[1050px] text-sm"><thead class="bg-default/70 text-left"><tr><th class="p-3">Orden / fecha</th><th class="p-3">Cliente</th><th class="p-3">Vehículo</th><th class="p-3">Prioridad</th><th class="p-3">Especialidad</th><th class="p-3">Mecánico sugerido</th><th class="p-3">Estado</th><th class="p-3 text-right">Acción</th></tr></thead><tbody><tr v-for="consulta in consultas.data" :key="consulta.id" class="border-t border-default transition hover:bg-default/45"><td class="p-3"><p class="font-mono font-semibold text-primary">{{consulta.orden||'Sin orden'}}</p><p class="text-xs text-muted">{{new Date(consulta.createdAt).toLocaleString('es-CO')}}</p></td><td class="p-3">{{consulta.cliente}}</td><td class="p-3 font-medium">{{consulta.vehiculo}}</td><td class="p-3"><UBadge :color="colorPrioridad(consulta.prioridad)" variant="subtle">{{consulta.prioridad}}</UBadge></td><td class="p-3">{{consulta.especialidad||'Por confirmar'}}</td><td class="p-3">{{consulta.mecanico||'Sin candidato compatible'}}</td><td class="p-3"><div class="flex flex-wrap gap-1"><UBadge variant="subtle">{{consulta.estado.replaceAll('_',' ')}}</UBadge><UBadge v-if="consulta.simulada" color="neutral" variant="outline">Simulado</UBadge></div></td><td class="p-3 text-right"><Link :href="route('ia.show',consulta.id)"><UButton label="Ver diagnóstico" icon="i-lucide-eye" size="sm" color="neutral" variant="ghost"/></Link></td></tr><tr v-if="!consultas.data.length"><td colspan="8" class="p-10 text-center"><UIcon name="i-lucide-brain-circuit" class="mx-auto size-8 text-dimmed"/><p class="mt-3 font-medium">No se encontraron diagnósticos IA</p><UButton v-if="can('ia.solicitar')" class="mt-3" label="Crear nuevo diagnóstico" @click="router.visit(route('ia.create'))"/></td></tr></tbody></table></div>
  <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p class="text-sm text-muted">Mostrando {{consultas.from??0}}-{{consultas.to??0}} de {{consultas.total}} diagnósticos</p><div class="flex gap-2"><UButton label="Anterior" color="neutral" variant="outline" :disabled="!consultas.prev_page_url" @click="consultas.prev_page_url&&router.visit(consultas.prev_page_url)"/><UButton label="Siguiente" color="neutral" variant="outline" :disabled="!consultas.next_page_url" @click="consultas.next_page_url&&router.visit(consultas.next_page_url)"/></div></div>
</div></template></UDashboardPanel></template>
